# Generated by Django 5.1.14 on 2025-12-02 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostgraduateProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Posgrado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Titulo")),
                (
                    "autor_name",
                    models.CharField(max_length=255, verbose_name="Nombre del Autor"),
                ),
                (
                    "director",
                    models.CharField(max_length=255, verbose_name="Director de Tesis"),
                ),
                (
                    "codirector",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Codirector de Tesis",
                    ),
                ),
                ("publication_year", models.IntegerField(verbose_name="Año")),
                ("abstract", models.TextField(verbose_name="Resumen/Abstract")),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="tesis_pdfs/", verbose_name="Archivo PDF"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tesis.postgraduateprogram",
                        verbose_name="Tipo de Posgrado",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
