# Generated by Django 5.1.14 on 2025-12-02 19:18

from django.db import migrations

def create_programs(apps, schema_editor):
    PostgraduateProgram = apps.get_model('tesis', 'PostgraduateProgram')
    programs = [
        "Maestría en Ciencias de Ing. Electrónica",
        "Doctorado en Ciencias de Ing. Electrónica",
        "Maestría en Ciencias de la Computación",
        "Doctorado en Ciencias de la Computación",
        "Maestría en Ciencias en Ing. Mecánica",
        "Doctorado en Ciencias en Ing. Mecánica",
        "Maestría en Ciencias en Ing. Mecatrónica",
        "Doctorado en Ciencias en Ing. Mecatrónica",
    ]
    for name in programs:
        PostgraduateProgram.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ("tesis", "0001_initial")
    ]

    operations = [
        migrations.RunPython(create_programs),
    ]
